function ALL = averageConds_ctrl(ALL)
an = fieldnames(ALL);
for a = 1:length(an)
    WKdata(:,:,a) = ALL.(an{a}).avgquad.WKdata;
    WKdataProp(:,:,a) = ALL.(an{a}).avgquad.WKdataProp;
    AlignData(:,:,a) = ALL.(an{a}).avgquad.AlignData;
    AlignDataProp(:,:,a) = ALL.(an{a}).avgquad.AlignDataProp;
    Dists(a,:) = ALL.(an{a}).avgquad.Dists;
%     BinnedTerrR(a,:) = ALL.(an{a}).avgquad.BinnedTerrR;
%     BinnedTerrRrot(a,:) = ALL.(an{a}).avgquad.BinnedTerrRrot;
    BinnedDists(:,:,a) = ALL.(an{a}).avgquad.BinnedDists;
    BinnedSPnum(a,:) = ALL.(an{a}).avgquad.BinnedSPnum;
    BinnedSPdist(a,:) = ALL.(an{a}).avgquad.BinnedSPdist;
    BinnedSPprop(a,:) = ALL.(an{a}).avgquad.BinnedSPprop;
    BinnedNPnum(a,:) = ALL.(an{a}).avgquad.BinnedNPnum;
    BinnedNPdist(a,:) = ALL.(an{a}).avgquad.BinnedNPdist;
    BinnedNPprop(a,:) = ALL.(an{a}).avgquad.BinnedNPprop;
    for b = 1:3
        BinnedAlign(:,:,a,b) = ALL.(an{a}).avgquad.BinnedAlign(:,:,1,b);
        BinnedAlignProp(:,:,a,b) = ALL.(an{a}).avgquad.BinnedAlignProp(:,:,1,b);
        BinnedWKdata(:,:,a,b) = ALL.(an{a}).avgquad.BinnedWKdata(:,:,1,b);
        BinnedWKdataProp(:,:,a,b) = ALL.(an{a}).avgquad.BinnedWKdataProp(:,:,1,b);
    end
    volOverlap(a,:) = ALL.(an{a}).avgquad.volOverlap;
    volOverlapRand(a,:) = ALL.(an{a}).avgquad.volOverlapRand;
end
    % overall data
    ALL.avg.WKdata = mean(WKdata,3,'omitnan');
    temp = ~isnan(WKdata);
    n = sum(temp,3);
    ALL.sem.WKdata = std(WKdata,[],3,'omitnan') ./ sqrt(n);
    ALL.avg.WKdataProp = mean(WKdataProp,3,'omitnan');
    temp = ~isnan(WKdataProp);
    n = sum(temp,3);
    ALL.sem.WKdataProp = std(WKdataProp,[],3,'omitnan') ./ sqrt(n);
    ALL.avg.AlignData = mean(AlignData,3,'omitnan');
    temp = ~isnan(AlignData);
    n = sum(temp,3);
    ALL.sem.AlignData = std(AlignData,[],3,'omitnan') ./ sqrt(n);
    ALL.avg.AlignDataProp = mean(AlignDataProp,3,'omitnan');
    temp = ~isnan(AlignDataProp);
    n = sum(temp,3);
    ALL.sem.AlignDataProp = std(AlignDataProp,[],3,'omitnan') ./ sqrt(n);
    ALL.avg.Dists = mean(Dists,1,'omitnan');
    ALL.avg.DistsAll = Dists;
    ALL.sem.Dists = std(Dists,[],1,'omitnan') ./ sqrt(a);
    % binned data
    ALL.avg.BinnedAlign = mean(BinnedAlign,3,'omitnan');
    temp = ~isnan(BinnedAlign);
    n = sum(temp,3);
    ALL.sem.BinnedAlign = std(BinnedAlign,[],3,'omitnan') ./ sqrt(n);
    ALL.avg.BinnedAlignProp = mean(BinnedAlignProp,3,'omitnan');
    temp = ~isnan(BinnedAlignProp);
    n = sum(temp,3);
    ALL.sem.BinnedAlignProp = std(BinnedAlignProp,[],3,'omitnan') ./ sqrt(n);
    ALL.avg.BinnedWKdata = mean(BinnedWKdata,3,'omitnan');
    temp = ~isnan(BinnedWKdata);
    n = sum(temp,3);
    ALL.sem.BinnedWKdata = std(BinnedWKdata,[],3,'omitnan') ./ sqrt(n);
    ALL.avg.BinnedWKdataProp = mean(BinnedWKdataProp,3,'omitnan');
    temp = ~isnan(BinnedWKdataProp);
    n = sum(temp,3);
    ALL.sem.BinnedWKdataProp = std(BinnedWKdataProp,[],3,'omitnan') ./ sqrt(n);
%     ALL.avg.BinnedTerrR = mean(BinnedTerrR,1,'omitnan');
%     ALL.sem.BinnedTerrR = std(BinnedTerrR,[],1,'omitnan') ./ sqrt(a);
%     ALL.avg.BinnedTerrRrot = mean(BinnedTerrRrot,1,'omitnan');
%     ALL.sem.BinnedTerrrot = std(BinnedTerrRrot,[],1,'omitnan') ./ sqrt(a);
    ALL.avg.BinnedDists = mean(BinnedDists,3,'omitnan');
    ALL.avg.BinnedDistsALL = BinnedDists;
    ALL.sem.BinnedDists = std(BinnedDists,[],3,'omitnan') ./ sqrt(a);
    ALL.avg.volOverlapPerAn = volOverlap;
    ALL.avg.volOverlapRandPerAn = volOverlapRand;
    ALL.avg.volOverlap = mean(volOverlap);
    ALL.sem.volOverlap = std(volOverlap) ./ sqrt(a);
    ALL.avg.volOverlapRand = mean(volOverlapRand);
    ALL.sem.volOverlapRand = std(volOverlapRand) ./ sqrt(a);
    %SP
    ALL.avg.BinnedSPnum = mean(BinnedSPnum,1,'omitnan');
    ALL.sem.BinnedSPnum = std(BinnedSPnum,[],1,'omitnan') ./ sqrt(a);
    ALL.avg.BinnedSPdist = mean(BinnedSPdist,1,'omitnan');
    ALL.sem.BinnedSPdist = std(BinnedSPdist,[],1,'omitnan') ./ sqrt(a);
    ALL.avg.BinnedSPprop = mean(BinnedSPprop,1,'omitnan');
    ALL.sem.BinnedSPprop = std(BinnedSPprop,[],1,'omitnan') ./ sqrt(a);
    %NP
    ALL.avg.BinnedNPnum = mean(BinnedNPnum,1,'omitnan');
    ALL.sem.BinnedNPnum = std(BinnedNPnum,[],1,'omitnan') ./ sqrt(a);
    ALL.avg.BinnedNPdist = mean(BinnedNPdist,1,'omitnan');
    ALL.sem.BinnedNPdist = std(BinnedNPdist,[],1,'omitnan') ./ sqrt(a);
    ALL.avg.BinnedNPprop = mean(BinnedNPprop,1,'omitnan');
    ALL.sem.BinnedNPprop = std(BinnedNPprop,[],1,'omitnan') ./ sqrt(a);
end